import Footer from "./components/Footer";
import Navigation from "./components/Navbar";
import "./globals.css";


export const metadata = {
  title: "Shell Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-gray-50 text-gray-800">
        <Navigation />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
